# Conclusion

In this final project, we conducted a detailed analysis of the overall crime situation and the relationship between the number of crimes and geographic location and time based on the New York State classified crime statistics data set. In the end, we also drew a clickable dynamic map based on D3, so that the audience can dynamically view the distribution of various crimes in various regions.

There are still many limitations in our project. First of all, due to the lack of monthly data in the data set, the relationship between the number of crimes and the month we proposed in datacheck could not be further studied. Secondly, although the data set is still updated in 2021, the latest time of the specific content still stays in 2019. In the project, we focused on the data of the past three years, hoping to get more warning data. However, due to the prevalence of COVID-19 from 2020 to 2021 and the occurrence of major social events such as  elections, the current social situation in the latest year has undergone great changes, and therefore more realistic crime data may not be presented. In addition, as mentioned in Chapter 2, this data set only contains data reported to the police agency, which does not equal all crime data. However, due to the limited time and resources of this project, we failed to solve the above problems. Instead, we completed the visual analysis of this data set under the premise of making certain assumptions.

In response to the above problems, we still have a lot of room for improvement in the future. First, we can find a more comprehensive data set through more channels, and introduce a wider geographic location and a longer time span into this project. For example, we can focus on analyzing the number of crimes and changes in the region since the COVID-19 outbreak in 2020, and put forward targeted recommendations for strengthening security in which region and time period. Second, we can try to use more visualization methods to analyze the data, and strive to dig out more valuable new information.

After this project, we have a new understanding of data analysis and visualization. Different from drawing the corresponding graphs as required in the homework, in actual scenarios we often need to analyze the data and choose the appropriate type of graphs to fully show the characteristics of the data. This is a necessary skill to become a good data worker. In addition, for areas that we are not familiar with, such as map drawing and the use of D3, we have also exercised to achieve this by combining class theories and searching network materials to improve engineering capabilities.



