--- 
title: "EDAV on NY Crimes"
author: "Ying Bi, Gaoge Liu, Hang Luo"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We are fortunate to live in today's era, enjoying freedom and peace. However, for a harmonious society, crime is an eternal stumbling block. Therefore, controlling crime is particularly important. Modern crimes can be roughly divided into two categories, violent crimes and property crimes. The former includes murder, rape and other vicious acts, while the latter is often related to money. Both types of crimes have a bad influence on the stability of society. For example, according to a recent report in the New York Times，an estimated 45,000 Americans are behind bars for thefts of less than $10,000 while the punishment doesn’t fit the crime. Not to mention violent crimes, once they happen, they are likely to bring devastating blows to individuals or families that can affect a lifetime.

2020 was an unfortunate year for the whole world. In a relatively turbulent social environment, we should pay more attention to crime and make our contribution to reducing and preventing crime.This is why we are interested in crime topics. After learning this course, we have the ability to explore the laws and characteristics of data through visualization. Considering that the national data volume is too large, in order to draw more detailed conclusions, we decided to focus on the state of New York where Columbia University is located. We found the criminal record statistics of various counties and police agencies in New York State since 1990, including violent crimes(murder, rape, robbery, etc) and property crimes(burglary, vehicle theft, etc). We hope to explore the law of crime in New York State through visual analysis of this data set, and provide our insights and suggestions.

In order to achieve our goal, we set up the following three questions：

1）In recent years, what is the distribution of the total number of crimes of different categories and subcategories? Which crime is the most common in number?

2）In recent years, how has the total number of crimes been geographically distributed? Are there any counties with high crime rates that are far ahead?

3）Extending the time frame to 30 years, how has the number of crimes in New York State changed during these 30 years? Is there a consistent trend?

It is worth noting that because the data set has a large range of missing values in 'month', and we have realized some of the limitations of the data set in the process of working, our above three questions are changed compared with those submitted during datacheck. Nevertheless, we still believe that the answers to the above three questions can help us better understand the crime situation in New York State.

In the following content, we will introduce the source of the dataset, the data pre-processing process, the plots drawn to answer the above three questions, and the analysis of our results.




